name: random-records-app

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: random-records-app-client
    container_name: app-client
    restart: unless-stopped
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - server

  mongo:
    image: mongo:8.0.9
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
    ports:
      - "27017:27017"
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data-volume:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/mongoexpress_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongoexpress_password
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongodb_root_username
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongodb_root_password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    secrets:
      - mongoexpress_username
      - mongoexpress_password
      - mongodb_root_username
      - mongodb_root_password
    depends_on:
      - mongo

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: random-records-app-server
    container_name: app-server
    restart: unless-stopped
    command: /usr/src/app/node_modules/.bin/nodemon server.ts
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5050:5050"
    secrets:
      - backblaze_app_key
      - backblaze_key_id
      - mongodb_basic_username
      - mongodb_basic_password
    depends_on:
      - mongo
    env_file: ./server/.env

secrets:
  backblaze_app_key:
    file: ./.backblaze_app_key_secret
  backblaze_key_id:
    file: ./.backblaze_key_id_secret
  mongodb_root_username:
    file: ./.mongodb_root_username_secret
  mongodb_root_password:
    file: ./.mongodb_root_password_secret
  mongodb_basic_username:
    file: ./.mongodb_basic_username_secret
  mongodb_basic_password:
    file: ./.mongodb_basic_password_secret
  mongoexpress_username:
    file: ./.mongoexpress_username_secret
  mongoexpress_password:
    file: ./.mongoexpress_password_secret

volumes:
  data-volume: