db = db.getSiblingDB("records_db");

db.createCollection("records");

db.records.insertMany([
  {
    title: "Music from Big Pink",
    artist: "The Band",
    year: 1968,
    image: "music-from-big-pink.webp",
  },
  {
    title: "Pet Sounds",
    artist: "The Beach Boys",
    year: 1966,
    image: "pet-sounds.webp",
  },
  {
    title: "Please Please Me",
    artist: "The Beatles",
    year: 1963,
    image: "please-please-me.webp",
  },
  {
    title: "Rubber Soul",
    artist: "The Beatles",
    year: 1965,
    image: "rubber-soul.webp",
  },
  {
    title: "Revolver",
    artist: "The Beatles",
    year: 1966,
    image: "revolver.webp",
  },
  {
    title: "Sgt. Pepper's Lonely Hearts Club Band",
    artist: "The Beatles",
    year: 1967,
    image: "sgt-peppers-lonely-hearts-club-band.webp",
  },
  {
    title: "The Beatles",
    artist: "The Beatles",
    year: 1968,
    image: "the-beatles.webp",
  },
  {
    title: "Abbey Road",
    artist: "The Beatles",
    year: 1969,
    image: "abbey-road.webp",
  },
  {
    title: "1967-1970",
    artist: "The Beatles",
    year: 1973,
    image: "1967-1970.webp",
  },
  {
    title: "The Great Twenty-Eight",
    artist: "Chuck Berry",
    year: 1982,
    image: "the-great-twenty-eight.webp",
  },
  {
    title: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
    artist: "David Bowie",
    year: 1972,
    image: "the-rise-and-fall-of-ziggy-stardust-and-the-spiders-from-mars.webp",
  },
  {
    title: "Blackstar",
    artist: "David Bowie",
    year: 2016,
    image: "blackstar.webp",
  },
  {
    title: "Chicago Transit Authority",
    artist: "Chicago",
    year: 1969,
    image: "chicago-transit-authority.webp",
  },
  {
    title: "London Calling",
    artist: "The Clash",
    year: 1979,
    image: "london-calling.webp",
  },
  {
    title: "The Doors",
    artist: "The Doors",
    year: 1967,
    image: "the-doors.webp",
  },
  {
    title: "Bringing It All Back Home",
    artist: "Bob Dylan",
    year: 1965,
    image: "bringing-it-all-back-home.webp",
  },
  {
    title: "Highway 61 Revisited",
    artist: "Bob Dylan",
    year: 1965,
    image: "highway-61-revisited.webp",
  },
  {
    title: "Blonde on Blonde",
    artist: "Bob Dylan",
    year: 1966,
    image: "blonde-on-blonde.webp",
  },
  {
    title: "Blood on the Tracks",
    artist: "Bob Dylan",
    year: 1975,
    image: "blood-on-the-tracks.webp",
  },
  {
    title: "Hotel California",
    artist: "Eagles",
    year: 1976,
    image: "hotel-california.webp",
  },
  {
    title: "Rumours",
    artist: "Fleetwood Mac",
    year: 1977,
    image: "rumours.webp",
  },
  {
    title: "The Colour and the Shape",
    artist: "Foo Fighters",
    year: 1997,
    image: "the-colour-and-the-shape.webp",
  },
  {
    title: "Concrete and Gold",
    artist: "Foo Fighters",
    year: 2017,
    image: "concrete-and-gold.webp",
  },
  { title: "Dookie", artist: "Green Day", year: 1994, image: "dookie.webp" },
  {
    title: "American Idiot",
    artist: "Green Day",
    year: 2004,
    image: "american-idiot.webp",
  },
  {
    title: "Are You Experienced",
    artist: "The Jimi Hendrix Experience",
    year: 1967,
    image: "are-you-experienced.webp",
  },
  {
    title: "Axis: Bold as Love",
    artist: "The Jimi Hendrix Experience",
    year: 1967,
    image: "axis-bold-as-love.webp",
  },
  {
    title: "Wavering Radiant",
    artist: "Isis",
    year: 2009,
    image: "wavering-radiant.webp",
  },
  {
    title: "Thriller",
    artist: "Michael Jackson",
    year: 1982,
    image: "thriller.webp",
  },
  {
    title: "Tapestry",
    artist: "Carole King",
    year: 1971,
    image: "tapestry.webp",
  },
  {
    title: "Led Zeppelin",
    artist: "Led Zeppelin",
    year: 1969,
    image: "led-zeppelin.webp",
  },
  {
    title: "Led Zeppelin II",
    artist: "Led Zeppelin",
    year: 1969,
    image: "led-zeppelin-ii.webp",
  },
  {
    title: "Led Zeppelin III",
    artist: "Led Zeppelin",
    year: 1970,
    image: "led-zeppelin-iii.webp",
  },
  {
    title: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    year: 1971,
    image: "led-zeppelin-iv.webp",
  },
  {
    title: "Houses of the Holy",
    artist: "Led Zeppelin",
    year: 1973,
    image: "houses-of-the-holy.webp",
  },
  {
    title: "In Through the Out Door",
    artist: "Led Zeppelin",
    year: 1979,
    image: "in-through-the-out-door.webp",
  },
  {
    title: "John Lennon/Plastic Ono Band",
    artist: "John Lennon",
    year: 1970,
    image: "john-lennon-plastic-ono-band.webp",
  },
  { title: "Blue", artist: "Joni Mitchell", year: 1971, image: "blue.webp" },
  {
    title: "Astral Weeks",
    artist: "Van Morrison",
    year: 1968,
    image: "astral-weeks.webp",
  },
  {
    title: "Moondance",
    artist: "Van Morrison",
    year: 1970,
    image: "moondance.webp",
  },
  {
    title: "Loveless",
    artist: "My Bloody Valentine",
    year: 1991,
    image: "loveless.webp",
  },
  {
    title: "The Downward Spiral",
    artist: "Nine Inch Nails",
    year: 1994,
    image: "the-downward-spiral.webp",
  },
  {
    title: "Nevermind",
    artist: "Nirvana",
    year: 1991,
    image: "nevermind.webp",
  },
  { title: "In Utero", artist: "Nirvana", year: 1993, image: "in-utero.webp" },
  {
    title: "MTV Unplugged in New York",
    artist: "Nirvana",
    year: 1994,
    image: "mtv-unplugged-in-new-york.webp",
  },
  { title: "Nirvana", artist: "Nirvana", year: 2002, image: "nirvana.webp" },
  {
    title: "Wish You Were Here",
    artist: "Pink Floyd",
    year: 1975,
    image: "wish-you-were-here.webp",
  },
  {
    title: "The Wall",
    artist: "Pink Floyd",
    year: 1979,
    image: "the-wall.webp",
  },
  {
    title: "Delicate Sound of Thunder",
    artist: "Pink Floyd",
    year: 1988,
    image: "delicate-sound-of-thunder.webp",
  },
  { title: "Doolittle", artist: "Pixies", year: 1989, image: "doolittle.webp" },
  {
    title: "The Sun Sessions",
    artist: "Elvis Presley",
    year: 1976,
    image: "the-sun-sessions.webp",
  },
  {
    title: "A Night at the Opera",
    artist: "Queen",
    year: 1975,
    image: "a-night-at-the-opera.webp",
  },
  {
    title: "OK Computer",
    artist: "Radiohead",
    year: 1997,
    image: "ok-computer.webp",
  },
  { title: "Ramones", artist: "Ramones", year: 1976, image: "ramones.webp" },
  {
    title: "Let It Bleed",
    artist: "The Rolling Stones",
    year: 1969,
    image: "let-it-bleed.webp",
  },
  {
    title: "Exile on Main St.",
    artist: "The Rolling Stones",
    year: 1972,
    image: "exile-on-main-st.webp",
  },
  {
    title: "It's Only Rock 'n Roll",
    artist: "The Rolling Stones",
    year: 1974,
    image: "its-only-rock-n-roll.webp",
  },
  {
    title: "Still Life",
    artist: "The Rolling Stones",
    year: 1982,
    image: "still-life.webp",
  },
  {
    title: "Never Mind the Bollocks, Here's the Sex Pistols",
    artist: "The Sex Pistols",
    year: 1977,
    image: "never-mind-the-bollocks-heres-the-sex-pistols.webp",
  },
  { title: "Horses", artist: "Patti Smith", year: 1975, image: "horses.webp" },
  {
    title: "Sonic Youth",
    artist: "Sonic Youth",
    year: 1982,
    image: "sonic-youth.webp",
  },
  {
    title: "Confusion Is Sex",
    artist: "Sonic Youth",
    year: 1983,
    image: "confusion-is-sex.webp",
  },
  { title: "Evol", artist: "Sonic Youth", year: 1986, image: "evol.webp" },
  { title: "Sister", artist: "Sonic Youth", year: 1987, image: "sister.webp" },
  {
    title: "Daydream Nation",
    artist: "Sonic Youth",
    year: 1988,
    image: "daydream-nation.webp",
  },
  { title: "Goo", artist: "Sonic Youth", year: 1990, image: "goo.webp" },
  { title: "Dirty", artist: "Sonic Youth", year: 1992, image: "dirty.webp" },
  {
    title: "Washing Machine",
    artist: "Sonic Youth",
    year: 1995,
    image: "washing-machine.webp",
  },
  {
    title: "A Thousand Leaves",
    artist: "Sonic Youth",
    year: 1998,
    image: "a-thousand-leaves.webp",
  },
  {
    title: "NYC Ghosts & Flowers",
    artist: "Sonic Youth",
    year: 2000,
    image: "nyc-ghosts-and-flowers.webp",
  },
  {
    title: "Rather Ripped",
    artist: "Sonic Youth",
    year: 2006,
    image: "rather-ripped.webp",
  },
  {
    title: "Born to Run",
    artist: "Bruce Springsteen",
    year: 1975,
    image: "born-to-run.webp",
  },
  {
    title: "Remain in Light",
    artist: "Talking Heads",
    year: 1980,
    image: "remain-in-light.webp",
  },
  {
    title: "The Joshua Tree",
    artist: "U2",
    year: 1987,
    image: "the-joshua-tree.webp",
  },
  {
    title: "Rattle and Hum",
    artist: "U2",
    year: 1988,
    image: "rattle-and-hum.webp",
  },
  {
    title: "Achtung Baby",
    artist: "U2",
    year: 1991,
    image: "achtung-baby.webp",
  },
  {
    title: "The Velvet Underground & Nico",
    artist: "The Velvet Underground",
    year: 1967,
    image: "the-velvet-underground-and-nico.webp",
  },
  { title: "Pinkerton", artist: "Weezer", year: 1996, image: "pinkerton.webp" },
  {
    title: "Who's Next",
    artist: "The Who",
    year: 1971,
    image: "whos-next.webp",
  },
  {
    title: "Yankee Hotel Foxtrot",
    artist: "Wilco",
    year: 2001,
    image: "yankee-hotel-foxtrot.webp",
  },
  {
    title: "Brian Wilson Presents Smile",
    artist: "Brian Wilson",
    year: 2004,
    image: "brian-wilson-presents-smile.webp",
  },
  {
    title: "Innervisions",
    artist: "Stevie Wonder",
    year: 1973,
    image: "innervisions.webp",
  },
  {
    title: "Pink Glitter Hummer Limo",
    artist: "Stucco",
    year: 2019,
    image: "pink-glitter-hummer-limo.webp",
  },
  {
    title: "Mahler: Symphony No. 4 in G",
    artist: "George Szell, Judith Raskin, The Cleveland",
    year: 2006,
    image: "mahler-symphony-no-4-in-g.webp",
  },
  {
    title: "Schubert Symphonies",
    artist: "Vienna Philharmonic Orchestra",
    year: 1972,
    image: "schubert-symphonies.webp",
  },
  {
    title: "King of the Delta Blues Singers",
    artist: "Robert Johnson",
    year: 1961,
    image: "king-of-the-delta-blues-singers.webp",
  },
  {
    title: "Because the Internet",
    artist: "Childish Gambino",
    year: 2013,
    image: "because-the-internet.webp",
  },
  {
    title: '"Awaken, My Love!"',
    artist: "Childish Gambino",
    year: 2016,
    image: "awaken-my-love.webp",
  },
  {
    title: "It Is What It Is",
    artist: "Thundercat",
    year: 2020,
    image: "it-is-what-it-is.webp",
  },
  {
    title: "Legend",
    artist: "Bob Marley and the Wailers",
    year: 1984,
    image: "legend.webp",
  },
  {
    title: "There's a Riot Goin' On",
    artist: "Sly and the Family Stone",
    year: 1971,
    image: "theres-a-riot-goin-on.webp",
  },
  {
    title: "What's Going On",
    artist: "Marvin Gaye",
    year: 1971,
    image: "whats-going-on.webp",
  },
  {
    title: "Curtis",
    artist: "Curtis Mayfield",
    year: 1970,
    image: "curtis.webp",
  },
  {
    title: "Live at the Regal",
    artist: "B.B. King",
    year: 1965,
    image: "live-at-the-regal.webp",
  },
  {
    title: "Amazing Grace",
    artist: "Aretha Franklin",
    year: 1972,
    image: "amazing-grace.webp",
  },
  {
    title: "Live at the Harlem Square Club, 1963",
    artist: "Sam Cooke",
    year: 1985,
    image: "live-at-the-harlem-square-club-1963.webp",
  },
  {
    title: "At Folsom Prison",
    artist: "Johnny Cash",
    year: 1968,
    image: "at-folsom-prison.webp",
  },
  {
    title: "Live at the Apollo",
    artist: "James Brown",
    year: 1963,
    image: "live-at-the-apollo.webp",
  },
  {
    title: "At Fillmore East",
    artist: "The Allman Brothers Band",
    year: 1971,
    image: "at-fillmore-east.webp",
  },
  {
    title: "Kind of Blue",
    artist: "Miles Davis",
    year: 1959,
    image: "kind-of-blue.webp",
  },
  {
    title: "Bitches Brew",
    artist: "Miles Davis",
    year: 1970,
    image: "bitches-brew.webp",
  },
  {
    title: "In Paris Festival International de Jazz",
    artist: "Miles Davis",
    year: 1949,
    image: "in-paris-festival-international-de-jazz.webp",
  },
  {
    title: "Coltrane's Sound",
    artist: "John Coltrane",
    year: 1964,
    image: "coltranes-sound.webp",
  },
  {
    title: "A Love Supreme",
    artist: "John Coltrane",
    year: 1965,
    image: "a-love-supreme.webp",
  },
  {
    title: "Giant Steps",
    artist: "John Coltrane",
    year: 1960,
    image: "giant-steps.webp",
  },
  { title: "Inside", artist: "Bo Burnham", year: 2021, image: "inside.webp" },
]);
